services:
  s-ui:
    image: ghcr.io/wanan9999/s-ui:latest
    container_name: s-ui
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    ports:
      - "2095:2095/tcp"
      - "2096:2096/tcp"
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - ./db:/app/db
      - ./cert:/app/cert
