services:
  s-ui:
    image: ghcr.io/wanan9999/s-ui:latest
    container_name: s-ui
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    network_mode: host
    volumes:
      - ./db:/app/db
      - ./cert:/app/cert
